name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip build-essential git bc swig \
            libncurses-dev libpython3-dev libssl-dev mtd-utils \
            fakeroot sudo cpio rsync cmake curl file

      - name: Configure Buildroot
        run: make rhodesisland_epass_defconfig

      - name: Build
        run: make
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buildroot-images
          path: |
            output/images/u-boot-sunxi-with-spl.bin
            output/images/zImage
            output/images/*.dtb
            output/images/rootfs.tar
            output/images/sdcard.img
            output/images/*.ubi.img
